# Generated by Django 4.1 on 2022-08-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopressmachine',
            name='length_dwg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autopressmachine',
            name='part_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='autopressmachine',
            name='part_point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
